---
name: Anna-Lena Delger
author: Anna-Lena Delger
url: "https://fwdc-ald.netlify.app"
language: en

creator:
  name: fwdc.
  author: fabian wohlgemuth
  url: "https://fabianwohlgemuth.de"
  # sourcecode: "https://github.com/wohfab/"
