---
name: Anna-Lena Delger
description: "Professional singer & conductor. Vocal jazz. Piano."
author: Anna-Lena Delger
url: "https://fwdc-ald.netlify.app"
language: en

creator:
  name: fwdc.
  author: fabian wohlgemuth
  url: "https://fabianwohlgemuth.de"
  # sourcecode: "https://github.com/wohfab/"
